version: '3.1'

services:
  app:
    build: ./shop_app
    container_name: shop_cont
    expose:
      - 5000
#    restart: always
    environment:
      - DATABASE_URL=postgresql://user:user_pw@db:5432/shop_db
      - PORT=5000

#    developers
    volumes:
      - ./shop_app:/shop_app/
#    developers

    depends_on:
      - db

  db:
    image: postgres
#    restart: always

#    developers
    volumes:
      - ./db_store:/var/lib/postgresql/data
    ports:
      - 5432:5432
#    developers

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user_pw
      - POSTGRES_DB=shop_db

  adminer:
    image: adminer
    expose:
      - 8080
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app
      - adminer
