"""empty message

Revision ID: 577a91cfc1c3
Revises: 122dd102bf94
Create Date: 2022-02-09 00:14:49.794495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a91cfc1c3'
down_revision = '122dd102bf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'article', ['art_code'])
    op.create_unique_constraint(None, 'category', ['cat_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'article', type_='unique')
    # ### end Alembic commands ###
