"""empty message

Revision ID: 80019e0d54b7
Revises: db9ec4956afc
Create Date: 2022-02-08 22:16:20.959458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80019e0d54b7'
down_revision = 'db9ec4956afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_shop_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_art_shop', sa.Integer(), nullable=True),
    sa.Column('rest', sa.Integer(), nullable=True),
    sa.Column('id_art', sa.Integer(), nullable=True),
    sa.Column('id_shop', sa.Integer(), nullable=True),
    sa.Column('action', sa.CHAR(length=1), nullable=True),
    sa.Column('last_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_art_shop'], ['art_shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'art_shop', ['id'])
    op.create_unique_constraint(None, 'article', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'shop', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'article', type_='unique')
    op.drop_constraint(None, 'art_shop', type_='unique')
    op.drop_table('art_shop_history')
    # ### end Alembic commands ###
