"""empty message

Revision ID: ad2b210e2008
Revises: 80019e0d54b7
Create Date: 2022-02-08 23:21:50.251409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2b210e2008'
down_revision = '80019e0d54b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'art_shop_history', ['id'])
    op.add_column('article', sa.Column('code', sa.Integer(), nullable=True))
    op.alter_column('article', 'art_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('shop', sa.Column('shop_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'shop_code')
    op.alter_column('article', 'art_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('article', 'code')
    op.drop_constraint(None, 'art_shop_history', type_='unique')
    # ### end Alembic commands ###
